application: iiser-kolkata
version: testing
runtime: python
api_version: 1

handlers:

- url: /~(.*)
  script: userhandler.py

- url: /static/(.*)\.html
  script: redirect.py

- url: /static
  static_dir: static

- url: /adduser0
  script: userhandler.py

- url: /adduser1
  script: userhandler.py

- url: /adduser2
  script: userhandler.py
  login: required

- url: /adduser3
  script: userhandler.py

- url: /adduser5
  script: userhandler.py
  login: required

- url: /useredit
  script: userhandler.py
  login: required

- url: /usereditsubmit
  script: userhandler.py
  login: required

- url: /adminedit0
  script: userhandler.py
  login: admin

- url: /adminedit1
  script: userhandler.py
  login: admin

- url: /admineditsubmit
  script: userhandler.py
  login: admin

- url: /students.html
  script: userhandler.py
  
- url: /students
  script: userhandler.py

- url: /img/(.*)
  script: userhandler.py

- url: /css/(.*)
  script: userhandler.py

- url: /
  script: main.py

- url: /reach
  static_files: static/reach.html
  upload: static/reach.html

- url: /magazine
  static_files: static/magazine.html
  upload: static/magazine.html

- url: /clubs
  static_files: static/clubs.html
  upload: static/clubs.html

- url: /faq
  static_files: static/faq.html
  upload: static/faq.html

- url: /campus-life
  static_files: static/campus-life.html
  upload: static/campus-life.html

- url: /info
  static_files: static/info.html
  upload: static/info.html

- url: /faq
  static_files: static/faq.html
  upload: static/faq.html

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)

